# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Veribilimi Istanbul
email: datascience.ml@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Veri biliminin farklı alanlarında çalışan insanların paylaşım ortamı.
    İş zekası, büyük veri, analitik, yapay öğrenme, yapay zeka, veri görselleştirme gibi alanlarla ilgileniyoruz.

    Grup yönetimi ve bilgi paylaşımında, açık kaynak yaklaşımını ve katılımcı yöntemi benimsiyoruz.
    veribilimi.ml kaynak kodlarını https://github.com/veribilimi/veribilimi.github.io
    adresinden göre bilirsiniz.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.veribilimi.ml" # the base hostname & protocol for your site
twitter_username: veribilimiist
github_username:  veribilimi

# Build settings
markdown: kramdown
